info_entry/config/routes.rb
Rails.application.routes.draw do
  get 'demo/index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usertests#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :usertests
  get 'page/index'

  resources :articles
  resources :users
  
  Rails.application.routes.draw do
  get 'demo/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :usertests
  get 'page/index'
  root 'page#index'
end

end

info_entry/app/models/article.rb
class Article < ActiveRecord::Base
end

info_entry/app/models/user.rb
class User < ActiveRecord::Base
end

info_entry/app/models/usertest.rb
class Usertest < ActiveRecord::Base
  has_secure_password
  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
            def to_s
    "#{first_name} #{last_name}"
  end
end

info_entry/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    Usertest.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

info_entry/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.fetch(:article, {})
    end
end

info_entry/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
  end
end

info_entry/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

info_entry/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    usertests = Usertest.find_by_email(params[:email])
    if usertests && usertests.authenticate(params[:password])
      session[:user_id] = usertests.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render :new
  end
 end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

info_entry/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:username])
    respond_to do |format|
    if @user.save
      
      format.html{redirect_to users_url, notice: 'User was sucessfully created'}
      format.json {render action:show, status: :created, location: @user}
    else
      render :new
        format.json {render json:@user.errors, status: :unprocessable_entity}
      
      
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
  end
end

info_entry/app/controllers/usertests_controller.rb
class UsertestsController < ApplicationController
  before_action :set_usertest, only: [:show, :edit, :update, :destroy]

  # GET /usertests
  # GET /usertests.json
  def index
    @usertests = Usertest.all
  end

  # GET /usertests/1
  # GET /usertests/1.json
  def show
  end

  # GET /usertests/new
  def new
    @usertest = Usertest.new
  end

  # GET /usertests/1/edit
  def edit
  end

  # POST /usertests
  # POST /usertests.json
  def create
    @usertest = Usertest.new(usertest_params)

    respond_to do |format|
      if @usertest.save
        format.html { redirect_to @usertest, notice: 'Usertest was successfully created.' }
        format.json { render :show, status: :created, location: @usertest }
      else
        format.html { render :new }
        format.json { render json: @usertest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usertests/1
  # PATCH/PUT /usertests/1.json
  def update
    respond_to do |format|
      if @usertest.update(usertest_params)
        format.html { redirect_to @usertest, notice: 'Usertest was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertest }
      else
        format.html { render :edit }
        format.json { render json: @usertest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertests/1
  # DELETE /usertests/1.json
  def destroy
    @usertest.destroy
    respond_to do |format|
      format.html { redirect_to usertests_url, notice: 'Usertest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usertest
      @usertest = Usertest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usertest_params
      params.require(:usertest).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

info_entry/app/helpers/application_helper.rb
module ApplicationHelper
end

info_entry/app/helpers/articles_helper.rb
module ArticlesHelper
end

info_entry/app/helpers/demo_helper.rb
module DemoHelper
end

info_entry/app/helpers/page_helper.rb
module PageHelper
end

info_entry/app/helpers/sessions_helper.rb
module SessionsHelper
end

info_entry/app/helpers/users_helper.rb
module UsersHelper
end

info_entry/app/helpers/usertests_helper.rb
module UsertestsHelper
end

info_entry/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

info_entry/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

info_entry/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

info_entry/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

info_entry/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

info_entry/app/views/demo/index.html.erb
<h1>Listing Users</h1>

<table>
   <thead>
       <tr>
           <th>Name</th>
           <th></th>
           <th></th>
       </tr>
            
  </thead>
 
 <tbody>
     <% user.each do |user| %>
     <tr>
         <td><%= user.name %></td>
         <td><%= link_to 'show' , user %></td>
          <td><%= link_to 'edit' , edit_user_path(user) %></td>
           <td><%= link_to 'destroy' , user , method: :delete, data: confirm: 'Are you sure?' %></td>
         
     </tr>
     <% end %>
 </tbody>
    
</table>

<% link_to 'New User' , new_user_path %>

info_entry/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InfoEntry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div id="user_header">
<% if current_user %>
Logged in as <%= current_user.email %>.
<%= link_to "Log Out", logout_path %>
<% else %>
<%= link_to "Sign Up", signup_path %> or
<%= link_to "Log In", login_path %>
<% end %>
</div>
<% flash.each do |key, value| %>
<%= content_tag(:div, class: "alert alert-#{key}") do %>
<p><%= value %></p>
<% end %>
<% end %>


</body>
</html>

info_entry/app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

info_entry/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

info_entry/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

info_entry/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

info_entry/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

info_entry/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

info_entry/app/views/usertests/_form.html.erb
<%= form_for(@usertest) do |f| %>
  <% if @usertest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertest.errors.count, "error") %> prohibited this usertest from being saved:</h2>

      <ul>
      <% @usertest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

info_entry/app/views/usertests/edit.html.erb
<h1>Editing Usertest</h1>

<%= render 'form' %>

<%= link_to 'Show', @usertest %> |
<%= link_to 'Back', usertests_path %>

info_entry/app/views/usertests/index.html.erb
<h1>Listing Usertests</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usertests.each do |usertest| %>
      <tr>
        <td><%= usertest.first_name %></td>
        <td><%= usertest.last_name %></td>
        <td><%= usertest.email %></td>
        <td><%= link_to 'Show', usertest %></td>
        <td><%= link_to 'Edit', edit_usertest_path(usertest) %></td>
        <td><%= link_to 'Destroy', usertest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usertest', new_usertest_path %>

info_entry/app/views/usertests/new.html.erb
<h1>New Usertest</h1>

<%= render 'form' %>

<%= link_to 'Back', usertests_path %>

info_entry/app/views/usertests/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @usertest.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @usertest.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usertest.email %>
</p>

<%= link_to 'Edit', edit_usertest_path(@usertest) %> |
<%= link_to 'Back', usertests_path %>